version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

  fastapi:
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - mongodb
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  producer:
    build:
      context: .
      dockerfile: producer.Dockerfile
    container_name: producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: job_matching_requests
    restart: always

  consumer:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    container_name: consumer
    depends_on:
      - kafka
      - mongodb
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: job_matching_requests
    restart: always
